version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: deadmin
    ports:
      - "8080:80"
    networks:
      - pg-network

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: deadmin
    volumes:
      - ./database_folder:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network

networks:
  pg-network:
